# System Configuration
# Version: 2.0 - Multiple spreadsheets support

google_sheets:
#テストデータ
  satisficing_test_data:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXXXXXXX"
  efa_unit_test_clean_28items_v2:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXXXXXXX" 
  efa_unit_test_skew_cross_28items_v2:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXXXXXXX"       
  efa_unit_test_collinear_28items_v2:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXXXXXXX"  
#    
#
# 本番データ
  items_30:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXX"
  items_30-Q19:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXX"    
  items_28-Q07:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXX"    
  items_28:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXX"
  items_29:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXX"
  rehab:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXX"
  interrater:
    spreadsheet_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    sheet_name: "XXXXXXXXXXXX"

authentication:
  cache_folder: ".secrets"
  email_auth: "example@example.com"
